### ISSUE TITLE
Vanilla compatibility fixes

### ISSUE THREAD

**Issue by NickDoom-IDKFA** [AryanWolf3D/Wolf4SDL#15]
[Sources_patch_temp.zip](https://github.com/AlumiuN/Wolf4SDL/files/3406082/Sources_patch_temp.zip)

IDK if they are already implemented (i've based my fixes on official Ubuntu repos, they can be obsolete).

Thanks for attention.

**Comment by AlumiuN** [comment]
Thank you for the suggestions (and code); generally speaking, the intention of Wolf4SDL (at least as it stands) is to maintain a reasonable level of code compatibility while allowing for higher resolutions and detail, as opposed to necessarily providing a vanilla experience. With that in mind, here's my thinking for the three features you've included:

1 (banded holo walls): I think I'll implement this as an optional, #define switched feature rather than as the default. (EDIT: has now been added to the repo)

2 (lower-res sky textures): This to me doesn't really change how much like a wall the textures look, it only serves to make them look jittery and garbled compared to their surroundings, so I don't think this should be implemented. However, it has given me an idea of having different internal and display resolutions and scaling the output accordingly, which will allow people who prefer the lower-res look to do so without having issues on modern OSes (or playing in a *really* small window).

3 (dithered shading): This is a decent idea for an optional enhancement, however as currently implemented it seems to only dither vertically and in a shifting pattern on the floor and ceiling, rather than in an evenly dithered static pattern, so I feel it could use some work.

**Comment by NickDoom-IDKFA** [comment]
1) Thanks :)
2) I don't like my texture shuffle, too. Maybe it's a better way to create moire on sky walls without rendering everything in low-res, but I hadn't found it yet :( Let's see how the low-res will look ^__^
3) For the speed reasons, I did it the "wolfensteinish" way (rough but quick, with whole columns and rows instead of single pixels), trying to mimic 80286 programming style :) It's no real reason to do it, so change it if you want to :)

> maintain a reasonable level of code compatibility while allowing for higher resolutions and detail, as opposed to necessarily providing a vanilla experience

"Similar to vanilla" in terms of the engine structure, not in terms of "look and feel"? I understand. These things are related, but they differ a lot.

**Comment by AlumiuN** [comment]
> "Similar to vanilla" in terms of the engine structure, not in terms of "look and feel"?

Yeah, and also keeping code either the same as or very close to the original DOS code so that existing tutorials (where appropriate) can be implemented on the SDL version with minimal additional effort.
